# Generated by Django 3.2.7 on 2021-09-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyectos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('estado', models.IntegerField()),
            ],
        ),
    ]
