# Generated by Django 3.2.7 on 2021-09-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id_proyectos',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
