# Generated by Django 3.2.6 on 2021-09-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('ACTIVADO', 'Activado'), ('CULMINADO', 'Culminado'), ('CANCELADO', 'Cancelado')], default='NUEVO', max_length=15),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
