# Generated by Django 3.2.6 on 2021-09-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20210922_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('ACTIVO', 'Activo'), ('CULMINADO', 'Culminado'), ('CANCELADO', 'Cancelado')], default='NUEVO', max_length=15),
        ),
    ]
