# Generated by Django 3.2.6 on 2021-09-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_usuario_hora_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('CULMINADO', 'Culminado'), ('CANCELADO', 'Cancelado')], max_length=15),
        ),
    ]
