# Generated by Django 3.2.6 on 2021-09-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('CULMINADO', 'Culminado'), ('CANCELADO', 'Cancelado')], max_length=15),
        ),
    ]
