# Generated by Django 3.2.6 on 2021-09-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='numSprint',
            field=models.IntegerField(default=0),
        ),
    ]
