# Generated by Django 3.2.6 on 2021-09-24 19:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0009_proyecto_numsprint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario_hora_trabajo',
            new_name='UsuarioHoraTrabajo',
        ),
    ]
