# Generated by Django 3.2.6 on 2021-09-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_rename_usuario_hora_trabajo_usuariohoratrabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariohoratrabajo',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='usuariohoratrabajo',
            name='user',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.DeleteModel(
            name='UsuarioHoraTrabajo',
        ),
    ]
