# Generated by Django 3.2.6 on 2021-10-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_auto_20211011_0234'),
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='sprint',
            name='numero_sprint',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='estado',
            field=models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=15),
        ),
        migrations.DeleteModel(
            name='HistoricalUserStory',
        ),
    ]
