# Generated by Django 3.2.6 on 2021-10-20 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_auto_20211011_0234'),
        ('sprint', '0002_auto_20211020_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
    ]
