# Generated by Django 3.2.6 on 2021-10-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0003_alter_sprint_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('ALTA', 'ALta'), ('EMERGENCIA', 'Emergencia')], max_length=15),
        ),
        migrations.DeleteModel(
            name='ProductBacklog',
        ),
    ]
