# Generated by Django 3.2.6 on 2021-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0004_auto_20211021_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='userstory',
            name='estado_us',
            field=models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PRODUCT_BACKLOG', 'Product Backlog')], default='PRODUCT_BACKLOG', max_length=15),
        ),
    ]
